#image: docker
#services:
#  - docker:dind
stages:
  - deploy
#variables:
#  GIT_STRATEGY: clone
#  GIT_CLEAN_FLAgs: none
#  GIT_CLONE_PATH: /home/deployer/debtor_lk
#  CI_BUILDS_DIR: /home/deployer/
#  CI_PROJECT_DIR: /home/deployer/

step-deploy-develop:
  stage: deploy
  script:
    - pwd
    - ls -la
    - tree

    - docker stack rm esia-dev

    - docker build . -f ./.docker/mariadb/Dockerfile -t mariadb-dev
    - docker build . -f .docker/php-fpm/Dockerfile  -t php-dev
    - docker build . -f .docker/nginx/Dockerfile -t nginx-dev

    - docker stack deploy -c docker-compose.yml -d=false esia-dev

#    - docker-compose -f develop.yml up -d
#    - docker exec esia-develop-php composer install
#    - docker exec esia-develop-php php artisan key:generate
#    - docker exec esia-develop-php php artisan migrate --seed
#    - docker exec esia-develop-php php artisan cache:clear
#    - docker exec esia-develop-php php artisan config:cache
#    - docker exec esia-develop-php php artisan route:cache
#    - docker exec esia-develop-php php artisan queue:restart

    - docker exec $(docker ps -aqf "ancestor=php-dev"| head -n 1) composer install
    - docker exec $(docker ps -aqf "ancestor=php-dev"| head -n 1) php artisan key:generate
    - docker exec $(docker ps -aqf "ancestor=php-dev"| head -n 1) php artisan migrate --seed
    - docker exec $(docker ps -aqf "ancestor=php-dev"| head -n 1) php artisan cache:clear
    - docker exec $(docker ps -aqf "ancestor=php-dev"| head -n 1) php artisan config:cache
    - docker exec $(docker ps -aqf "ancestor=php-dev"| head -n 1) php artisan route:cache
    - docker exec $(docker ps -aqf "ancestor=php-dev"| head -n 1) php artisan queue:restart

  only:
    - develop

step-deploy-main:
  stage: deploy
  script:
    - docker-compose -f prod-esia.yml up -d
  only:
    - main