services:
  nginx-dev:
    image: nginx-dev
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.swarm.network=proxy
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: always

  php-dev:
    image: php-dev
    volumes:
      - storage-php-dev:/var/www/html/storage
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: always

  mariadb-dev:
    image: mariadb-dev
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: esia-database
      MARIADB_USER: ${DB_USERNAME:-esia-local}
      MARIADB_PASSWORD: ${DB_PASSWORD:-esia-local}
      MARIADB_ROOT_PASSWORD: 'secret'
      MARIADB_ROOT_HOST: "%"
    volumes:
      - /home/deployer/debtor_lk/backend/docker/mariadb/data:/var/lib/mysql
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: always

  redis-dev:
    image: redis:latest
    volumes:
      - /home/deployer/debtor_lk/backend/docker/redis/data:/data
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    restart: always

networks:
    proxy:
        driver: overlay
        external: true
volumes:
    storage-php-dev:
