services:
    nginx:
        container_name: esia-develop-nginx
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
#        ports:
#            - "8000:80"
        depends_on:
           - php
#        volumes:
#            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#            - ./app:/var/www/html
        networks:
            - esia-networks

    php:
        container_name: esia-develop-php
        build:
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
#        volumes:
#            - .docker/php/php.ini:/usr/local/etc/php/php.ini
#            - ./app:/var/www/html
#            - ./storage:/var/www/html/storage
#            - .env:/var/www/html/.env
        networks:
            - esia-networks

    mariadb:
        container_name: esia-develop-mariadb
        build:
            context: .
            dockerfile: .docker/mariadb/Dockerfile
        ports:
            - "3306:3306"
        environment:
            MARIADB_DATABASE: esia-database
            MARIADB_USER: ${DB_USERNAME:-esia-local}
            MARIADB_PASSWORD: ${DB_PASSWORD:-esia-local}
            MARIADB_ROOT_PASSWORD: 'secret'
            MARIADB_ROOT_HOST: "%"
        volumes:
            - /home/deployer/debtor_lk/backend/docker/mariadb/data:/var/lib/mysql
        networks:
            - esia-networks

    redis:
        image: redis
        container_name: esia-develop-redis
        volumes:
            - /home/deployer/debtor_lk/backend/docker/redis/data:/data
        networks:
            - esia-networks

networks:
    esia-networks:
        external: true
