services:
    nginx-dev:
        image: nginx-dev
#        ports:
#            - "8000:80" 
        depends_on:
           - php
        labels:
          - traefik.enable=true

#        volumes:
#            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#            - ./app:/var/www/html
        networks:
#            - esia-networks
          - proxy

    php-dev:
        image: php-dev
#        build:
#            context: .
#            dockerfile: .docker/php-fpm/Dockerfile
        volumes:
#            - .docker/php/php.ini:/usr/local/etc/php/php.ini
#            - ./app:/var/www/html
            - /home/deployer/debtor_lk/backend/storage:/var/www/html/storage
#            - .env:/var/www/html/.env
        environment:
            MAIL_MAILER: log
            MAIL_SCHEME: null
            MAIL_HOST: 192.168.152.6
            MAIL_PORT: 587
#            MAIL_ENCRYPTION: tls
            MAIL_USERNAME: noreply
            MAIL_PASSWORD: s2fvLWxkCLkR
            MAIL_FROM_ADDRESS: "noreply@gkcdu.ru"
            MAIL_FROM_NAME: "${APP_NAME}"
        networks:
          - proxy

    mariadb-dev:
#        container_name: esia-develop-mariadb
        image: mariadb-dev
        ports:
            - "3306:3306"
        environment:
            MARIADB_DATABASE: esia-database
            MARIADB_USER: ${DB_USERNAME:-esia-local}
            MARIADB_PASSWORD: ${DB_PASSWORD:-esia-local}
            MARIADB_ROOT_PASSWORD: 'secret'
            MARIADB_ROOT_HOST: "%"
        volumes:
            - /home/deployer/debtor_lk/backend/docker/mariadb/data:/var/lib/mysql
        networks:
          - proxy
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                - node.role == manager
    redis-dev:
        image: redis:latest
#        container_name: esia-develop-redis
        volumes:
            - /home/deployer/debtor_lk/backend/docker/redis/data:/data
        networks:
          - proxy
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                - node.role == manager
networks:
    proxy:
        driver: overlay
        external: true
